### ISSUE TITLE
Query permalinks of long URLs return 500 

### ISSUE THREAD

**Issue by LaurensRietveld** [YASGUI/YASGUI#68]
Logs show:
```
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/usr/local/yasgui/node_modules/express/node_modules/send/index.js:245:31)
    at SendStream.send (/usr/local/yasgui/node_modules/express/node_modules/send/index.js:564:19)
    at onstat (/usr/local/yasgui/node_modules/express/node_modules/send/index.js:624:10)
    at Object.oncomplete (fs.js:107:15)
```

an example: http://yasgui.org/short/EkvKiN96

**Comment by LaurensRietveld** [comment]
Upgrading to node 0.12 fixed this issue.
If you're using nginx with proxy forwards, not that you might need to change the config as well by increasing the proxy buffer. Add e.g.: 
```
http {
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
}

```
